import type { Metadata } from "next";
import { Inter, Amiko, Kanit } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import { Mybar } from "@/components/Mybar/Mybar";

const kanit = Kanit({ subsets: ["latin"], weight: "400", display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Sidebar />
        <Mybar />
        <div className="ml-[270px] mr-[300px] p-[24px]">{children}</div>
      </body>
    </html>
  );
}
